### ISSUE TITLE
Adding simple chess features

### ISSUE THREAD

**Issue by bjornregnell** [litan/kojo#47]
Here we can discuss things to add related to the Chess project.

**Comment by bjornregnell** [comment]
The Swedish Turtle is here: https://github.com/litan/kojo/blob/master/src/main/scala/net/kogics/kojo/lite/i18n/svInit.scala

**Comment by IdaRasmark** [comment]
Yes I have some functionalities that I want to add. Here is a list of functions:

- board()
Draws the chessboard starting in (0,0) with 25 pixels squares. I think for now the easiest way is to always begin to draw in (0,0), since we have the startingPoint()-function.

-notation()
Prints the numbers and letters around the chessboard. I think this can be made into an argument that is optional in the board()-function. Something like: board("notation") or board(1). What do you think? 

- startingPoint(square:String)
Accepted input-strings are A-H in combination with 1-8. Example "A1" or "G5". The turtle is placed on that square on the board.

The rest ones I am not so sure about whether if they should be made or not.. feels a bit like if there is functions like this, maybe other functions like moveLeft()/moveRight() can be made aswell. I dont know...  Please let me know that you think!

-backwards()
Moves the turtle backwards 25 pixls without moving the direction of the turtle

-diagonalUpLeft() # I dont think I like the name of this function
Moves the turtle to the square that is diagonally up to the left of the turtle. Does not change the direction of the turtle. 

-diagonalUpRight()
-diagonalDownRight()
-diaogonalDownLeft()

**Comment by IdaRasmark** [comment]
@litan I and Björn were talkning about where you think it's a good idea for me to put the code? Maybe it's good to do it like you have done before: That the real code is made in the english turtle, and then the swedish commands just calls the english ones. Do you think that sounds like a good idea? In what file would that be?

**Comment by litan** [comment]
As a first cut, how about if we use the approach that we once discussed, and that I have been using for a lot of the recent kojo extensions (like kojo-ai, kojo-arduino etc).

The approach (as it might apply to the chess stuff) is roughly the following:
* define all the required commands and functions in a kojo file. Let's say this file is chess.kojo.
* put this file under the kojo resources dir.

Now, kids can write something like this in the script editor:
```
// #include chess
board()
startingPoint(whatever)
// etc
```
How does that sound?

chess.kojo can include the core commands defined in English, and Swedish versions of these commands can currently be in the same file - and can call the English versions. Once we have something up and running, we can figure out how to separate these (the English and Swedish versions) out nicely and cleanly...

**Comment by bulent2k2** [comment]
Can you please provide an overview of this project?

I am interested in developing a Turkish Checkers script (spin off from 
Othello code) and we can probably share most of the core API...

Bulent

On 2021-10-08 12:49, Bjorn Regnell wrote:

> Here we can discuss things to add related to the Chess project.
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] https://github.com/litan/kojo/issues/47
[2]

**Comment by bulent2k2** [comment]
Please ignore my last comment. Some of the earlier comments I missed clarify things for me for now.

**Comment by bjornregnell** [comment]
OK thanks @bulent2k2 . The project is focused on very simple code snippets for young kids related to chess, e.g. drawing a chess board and making pieces move.  It is connected to CHESSPLUS and a project lead by Jesper Hall. More info here: 
* https://chessplus.net/
* https://chessplus.net/smartmethod/
The project to connect CHESSPLUS and Kojo is still in its early stages and has been somewhat delayed, but @IdaRasmark at the Science Center of Lund University in Sweden is working on exoeriments for kids.

**Comment by IdaRasmark** [comment]
Hey guys! Now, after a very long time, I have added the chess commands in the way that you described @litan. I haven't made a pull request yet, I can do that if you want me to! Otherwise you can look at what I added here: https://github.com/IdaRasmark/kojo/tree/master/src/main/resources/chess 

As i was testing the code I noted that a few commands didn't work in webb-kojo:

- position.x
- position.y
- jumpTo(x,y)
- saveStyle()

I manage (I think) to work around that. But just FYI :) 

Please come with feedback!

**Comment by litan** [comment]
Sounds good @IdaRasmark. I will manually pull this in tomorrow (so there is no need for a pull request).

With regard to iKojo:
- position is not supported
- jumpTo(x, y) can be replaced with setPosition(x, y)
- saveStyle - can be added in a future version

> I manage (I think) to work around that. 
So things seem to be working fine with your workaround? Feel free to save your iKojo version of the chess commands as a fiddle and send me a link.

**Comment by litan** [comment]
I have integrated chess.kojo. Here's some sample code that uses the script:
```scala
// #include /chess.kojo
clear()
notation()
board()
startingPoint("F1")
diagonalNortheast()
forward()
backward()
```

This will be available in the next version of Kojo, which will be released in the next day or two.
@IdaRasmark you are welcome to keep refining chess.kojo. The refinements will become available in successive Kojo releases , which happen as frequently as once a month -- depending on what new features need to go out to users.

**Comment by litan** [comment]
> This will be available in the next version of Kojo, which will be released in the next day or two.

FYI, a new version of Kojo, which includes the chess script, has been released.

**Comment by IdaRasmark** [comment]
Great! I have already made some changes that will be finnished in a day or two. 

setPosition(x,y) is a good command, I will remember that in the future :)

I have some questions:

- Will/can chess.kojo be accessed in webb-kojo? Is there a lot of work that need to be done to make that work?
- is it possible for me to change the code so that you only need to write the command (example: backward, diagonalNorthEast) without paranthesis  for the commands that does not need arguments? 
- When I feel ready with my changes, I will just make a pull request right? 

This was fun!

**Comment by litan** [comment]
> Will/can chess.kojo be accessed in webb-kojo? Is there a lot of work that need to be done to make that work?

I will have to explore (currently iKojo has no include mechanism). 

> is it possible for me to change the code so that you only need to write the command (example: backward, diagonalNorthEast) without paranthesis for the commands that does not need arguments?

No change needed in chess.kojo. This should already work!

> When I feel ready with my changes, I will just make a pull request right?

Yes, that sounds good.

**Comment by litan** [comment]
Features added via https://github.com/litan/kojo/pull/57
